//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_QLDUAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.UserTasks = new HashSet<UserTask>();
            this.Links = new HashSet<Link>();
            this.Links1 = new HashSet<Link>();
            this.ToDoes = new HashSet<ToDo>();
            this.Comments = new HashSet<Comment>();
        }
    
        public string ID { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string ProjectID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ParentID { get; set; }
        public Nullable<double> Progress { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int rowID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<UserTask> UserTasks { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<Link> Links1 { get; set; }
        public virtual ICollection<ToDo> ToDoes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
