//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_QLDUAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> HourWork { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string TaskID { get; set; }
        public Nullable<bool> FinishTask { get; set; }
        public string UserID { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
