//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_QLDUAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProject
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> isLeader { get; set; }
        public string Classification { get; set; }
        public Nullable<System.DateTime> ClassificationDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
