//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_QLDUAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notes = new HashSet<Note>();
            this.UserProjects = new HashSet<UserProject>();
            this.UserTasks = new HashSet<UserTask>();
            this.Projects = new HashSet<Project>();
            this.ToDoes = new HashSet<ToDo>();
            this.Comments = new HashSet<Comment>();
        }
    
        public string ID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
        public string RoleID { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<UserProject> UserProjects { get; set; }
        public virtual ICollection<UserTask> UserTasks { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ToDo> ToDoes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
